### ISSUE TITLE
Fields with default values show as required

### ISSUE THREAD

**Issue by NickLarsenNZ** [StephaneBour/actions-calver#3]
With fields set as `required`, I get warnings in my IDE:

https://github.com/StephaneBour/actions-calver/blob/13a19de7c09146a73955d9121078bde69d48f2a6/action.yml#L18-L21

![image](https://user-images.githubusercontent.com/10092581/146342236-97eed9df-d4d5-4264-8501-2268a25039a6.png)

**Comment by StephaneBour** [comment]
it's fixed, thank you
